### ISSUE TITLE
question about the function of dataSummarizationLiP 

### ISSUE THREAD

**Issue by jinaanna** [Vitek-Lab/MSstatsLiP#28]
An error occured when I run this code. I have checked the data format and found nothing abnormal. I can't figure out what  the error means.  Could you please give me some tips for solving this issue?
![image](https://user-images.githubusercontent.com/91006223/182007253-25f7db73-cc13-4ae9-98d1-c99dd2c87a14.png)

![image](https://user-images.githubusercontent.com/91006223/182007598-e023ce34-752b-4041-825f-4f3d8f77d21b.png)

**Comment by devonjkohler** [comment]
Hi @jinaanna,

Would you be able to provide more information, such as the top rows of your input data? It is challenging to determine the root of the issue without more info.

Devon

**Comment by jinaanna** [comment]
OK. I have provided the top  rows of my data in the attachment. Do not hesitate to contact me if there is any question with my data format or other issues. Thank you so much!


---- Replied Message ----
| From | Devon ***@***.***> |
| Date | 8/10/2022 00:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Vitek-Lab/MSstatsLiP] question about the function of dataSummarizationLiP (Issue #28) |

Hi @jinaanna,

Would you be able to provide more information, such as the top rows of your input data? It is challenging to determine the root of the issue without more info.

Devon

**Comment by Clovernana** [comment]
> 
New issues occured when I run this code on another computer. The R directly collapsed when I run the code described above when the whole process ran about 76%. Could you please give me some help in solving this trouble?

Thank you, and I'm looking forward to your reply.

**Comment by devonjkohler** [comment]
How large is your dataset? Looking at the image in this issue, it seems like there was a similar problem, ie the summarization gets to about 75% and then there is an error about not being able to allocate the vector. This is most likely due to your computer running out of RAM while attempting to perform summarization.

**Comment by Clovernana** [comment]
> How large is your dataset? Looking at the image in this issue, it seems like there was a similar problem, ie the summarization gets to about 75% and then there is an error about not being able to allocate the vector. This is most likely due to your computer running out of RAM while attempting to perform summarization.

Really large， about 2G per file since I analysised the human proteome using DIA (including LiPRawData and TrPRawData).  In this condition, is there any way to make the data analysis go on ? Is there any other package or workflow to be recommended for me ?

**Comment by devonjkohler** [comment]
In large DIA datasets there can be a very large number of features per protein. I would first recommend trying to use less features, which you can set in the `dataSummarizationLiP` function. I've included an example script below for this. Let me know if this works!

dataSummarizationLiP(
  data,
  featureSubset = "topN",
  featureSubset.LiP = "topN",
  min_feature_count = 50, # Try adjusting these counts
  min_feature_count.LiP = 50)

**Comment by Clovernana** [comment]
> In large DIA datasets there can be a very large number of features per protein. I would first recommend trying to use less features, which you can set in the `dataSummarizationLiP` function. I've included an example script below for this. Let me know if this works!
> 
> ```
> dataSummarizationLiP(
>   data,
>   featureSubset = "topN",
>   featureSubset.LiP = "topN",
>   min_feature_count = 50, # Try adjusting these counts
>   min_feature_count.LiP = 50)
> ```

R falied to run. Same error as desrcibed above.

**Comment by devonjkohler** [comment]
Are you currently setting `MBimpute = TRUE`? Can you try to set it to `FALSE`?

**Comment by Clovernana** [comment]
> Are you currently setting `MBimpute = TRUE`? Can you try to set it to `FALSE`?

OK. I have added that but R still collapsed. 

`dataSummarizationLiP(
  MSstatsLiP_data,
  featureSubset = "topN",
  featureSubset.LiP = "topN",
  min_feature_count = 50, # Try adjusting these counts
  min_feature_count.LiP = 50,
  MBimpute = FALSE, 
  use_log_file = FALSE, 
  append = FALSE)`

**Comment by devonjkohler** [comment]
Hi, Sorry for the delayed response, I have been doing some testing on my end to try to see what might be most effective. There are two things I was wondering if you could try.

First can you try to run the workflow with only the LiP data? I am trying to pinpoint exactly what part of your analysis is causing the issue. IE your code would look something like below.

```
data <- read.delim("LiP_Data.csv")
fasta <- "fasta_data.fasta"
tidyFasta(fasta)
MSstatsLiP_data <- SpectronauttoMSstatsLiPFormat(data, fasta)
MSstatsLiP_Summarized <- dataSummarizationLiP(MSstatsLiP_data)
```

Second, did you try to adjust that `min_feature_count` variable to smaller amounts? Could you try to set it to something really small like 3?
