### ISSUE TITLE
Spectronaut output

### ISSUE THREAD

**Issue by She1111** [Vitek-Lab/MSstatsLiP#30]
Hi,

Thank you for your great effort to develop this package! As I do not use Spectronaut or Skyline to analysis my data (instead of MaxQuant and DIA-NN), I wonder whether output files from MaxQuant (.txt) or DIA-NN (.tsv) can be converted to compatible format in MSstatsLiP? Which columns should it contain?
Thanks in advance!

Best regards,
Shel

**Comment by devonjkohler** [comment]
Hi @She1111,

We do not have a dedicated MSstatsLiP converter for MaxQ currently, however it should be fairly straight forward to leverage the base MSstats converter for this. I've included a script below that I think should work. Give it a shot and let me know if you run into any errors. On a side note, if you can share your data with me, I would be happy to build a dedicated MaxQ converter for this package.

Best,
Devon

```
library(MSstats)
library(MSstatsLiP)

lip_ev = read.csv("lip_evidence.csv")
lip_pg = read.csv("lip_pg.csv")
lip_annot = read.csv("lip_annot.csv")

msstats_lip_df = MSstats::MaxQtoMSstatsFormat(lip_ev, lip_annot, lip_pg)
msstats_lip_df$ProteinName = paste(msstats_lip_df$ProteinName, msstats_lip_df$PeptideSequence, sep="_")

trp_ev = read.csv("trp_evidence.csv")
trp_pg = read.csv("trp_pg.csv")
trp_annot = read.csv("trp_annot.csv")

msstats_trp_df = MSstats::MaxQtoMSstatsFormat(lip_ev, lip_annot, lip_pg)
msstats_trp_df$ProteinName = paste(msstats_trp_df$ProteinName, msstats_trp_df$PeptideSequence, sep="_")

msstatslip_input = list(LiP = msstats_lip_df, TrP = msstats_trp_df)

dataSummarizationLiP(msstatslip_input )
```

**Comment by She1111** [comment]
Hi Devon,

Thank you for your kind reply! Then of course I would like to try the code you suggested first and share this data with you!

Best,
Shel

**Comment by She1111** [comment]
Hi Devon,

Now I am trying to import DIA-NN output to MSstatsLiP for analyzing. I find that MSstatsConvert has released DIA-NN converter but there is still no start-to-end tutorial for it. Could you please have a look?

Thanks in advance!

Best,
Shel
