### ISSUE TITLE
DIA-NN output issues

### ISSUE THREAD

**Issue by She1111** [Vitek-Lab/MSstatsLiP#31]
Hi,

Thank you for your great effort to develop this R package! I am getting in trouble with the analysis procedure using output from DIA-NN-MSstatsConverter. I am using the latest version of MSstatsConvert and it can detect fragment intensity while the old version cannot. But it cannot distinguish 'stripped sequence' and 'modified sequence' as it will affect oxidation filtering (Mateusz will update MSstats). In my case, the 'modified sequence' is identified as 'PEPTIDE'. It looks like:
```r
> unique(MSstatsLiP_Summarized_1min[["LiP"]][["FeatureLevelData"]][["PEPTIDE"]])

 [988] LIEEQIR_2                                   
 [989] LLEEAPSPALTAELR_2                           
 [990] LLEEAPSPALTAELR_3                           
 [991] LLEEAPSPALTAELRK_2                          
 [992] LLEEAPSPALTAELRK_3                          
 [993] NEIGFPVMIK_2                                
 [994] RALNDTIITGVPTTINYHK_3                       
 [995] RDHGINFIGPNPDSIR_3                          
 [996] SDYVVPPSYDSLLGK_2                           
 **[997] SEAAAAFGNDGC(UniMod:4)YLEK_2**                
 [998] SVDLIEEQIR_2                                
 [999] SYLPSGGPFVR_2                               
**[1000] TAHEMGIPC(UniMod:4)VAVYSTIDK_2**  
``` 
Dose 'UniMod:4' in the sequence affect statistics results?
Also, when I check trypticity distribution using ```trypticHistogramLiP```, it returns HT ratio of 100%. 

Thanks in advance!

Best regards,
Shel

**Comment by devonjkohler** [comment]
Hey @She1111,

Sorry for the delayed response, I missed this issue when you originally posted. I have not worked with DIA-NN output with this package and the modifications ("UniMod") will definitely mess with the tryptic calculations. I can work toward a dedicated DIA-NN MSstatsLiP converter to deal with this. 

In terms of your second question, this result is a bit odd but could be fine (it's a bit hard to tell without looking at the underlying data). If you could shoot over a small subset of your results I would be happy to double check that they look ok based off the model calculations.

Devon

**Comment by She1111** [comment]
> Hey @She1111,
> 
> Sorry for the delayed response, I missed this issue when you originally posted. I have not worked with DIA-NN output with this package and the modifications ("UniMod") will definitely mess with the tryptic calculations. I can work toward a dedicated DIA-NN MSstatsLiP converter to deal with this.
> 
> In terms of your second question, this result is a bit odd but could be fine (it's a bit hard to tell without looking at the underlying data). If you could shoot over a small subset of your results I would be happy to double check that they look ok based off the model calculations.
> 
> Devon

Hi Devon,

Thank you so much for your reply! I would like to share with you a part of data, both TrP and LiP data original from DIA-NN. They are ~300 MB in total. How could I share the data to you?

Thanks again!!

Best regards,
Shel

**Comment by devonjkohler** [comment]
Hi @She1111,

You can email them to me if that works: kohler.d@northeastern.edu

Quick question, as far as I can tell there are three ways to deal with these modified peptides. We can treat them as individual LiP peptides and model them separately, we can treat them as features of the unmodified peptide and model them together with the unmod proteoform, or we can simply remove them all together. Do you have an opinion on how you would like to use these peptides?

Devon

**Comment by She1111** [comment]
> Hi @She1111,
> 
> You can email them to me if that works: [kohler.d@northeastern.edu](mailto:kohler.d@northeastern.edu)
> 
> Quick question, as far as I can tell there are three ways to deal with these modified peptides. We can treat them as individual LiP peptides and model them separately, we can treat them as features of the unmodified peptide and model them together with the unmod proteoform, or we can simply remove them all together. Do you have an opinion on how you would like to use these peptides?
> 
> Devon

Hi Devon,

I would like to keep these peptides as unmodified peptides as I would not take these modifications in my case.

Best regards,
Shel

**Comment by devonjkohler** [comment]
Hi @She1111 

The DIA-NN converter has been added to the package. It is available in Github right now and will be up on Bioconductor by tomorrow around noon EDT. 

Devon

**Comment by xueeeeepeng** [comment]
@devonjkohler @She1111 The article saysThe article says  for the LiP samples, apply a semi-speciﬁc tryptic digestion rule; for the TrP samples, apply a speciﬁc tryptic digestion rule.But as far as I know, there is no way to set up semi-trypsin digestion in DIANN database search. Will this affect the subsequent results?
