### ISSUE TITLE
NaN issue while using Barcode function

### ISSUE THREAD

**Issue by jazzminda** [Vitek-Lab/MSstatsLiP#32]
Dear MSstatsLiP-Team,

thank you so much for creating comprehensive information to evaluate LiP-MS data! I could follow all your code and information except in one part, where I am hoping you can help me.

While trying to produce Barcode-Plots, I have run into an issue with the following error message:

```
Error in if (temp.coverage.df[idx, sig] == TRUE) { : 
  missing value where TRUE/FALSE needed
```

The exact command that I used was:

```
StructuralBarcodePlotLiP(MSstatsLiP_model, fasta_file,
                         model_type = "Unadjusted",
                         address=FALSE)
```

It would be great if you could help me figure out where in the model/dataframe the issue comes from!

Thank you in advance,
Jasmin

**Comment by jazzminda** [comment]
Hi @devonjkohler ,

Thank you for getting back so fast!

I attached a small subset of my dataset (MSstatsLiP_model$LiP_model). 
[LiP_Data_example.csv](https://github.com/Vitek-Lab/MSstatsLiP/files/13046715/LiP_Data_example.csv)

The fasta file only contained one protein sequence in Uniprot format. I hope this helps!

Jasmin

**Comment by devonjkohler** [comment]
Hey @jazzminda,

I just pushed a fix to Github that I think fixes this issue. There was a problem with NAs that was causing the plot to fail. I've also added the fix to Bioconductor, but since the next Bioc release is on Wednesday I am waiting on the release to push it there.

Let me know if this fixes the plot for you!

Devon

**Comment by jazzminda** [comment]
Hi @devonjkohler,

great! I just retried it with your fix and the function worked and I could successfully create a barcode plot.
Thank you for the quick fix!

Best,
Jasmin
